### ISSUE TITLE
Drop support for Python2

### ISSUE THREAD

**Issue by kdheepak** [dss-extensions/OpenDSSDirect.py#114]
What are your thoughts about dropping support for Python2? 

We could remove lines like `from __future__ import absolute_import` like here:

https://github.com/dss-extensions/OpenDSSDirect.py/blob/e8426ff1b78731d4b007a8d415f46361e8adfc43/opendssdirect/utils.py#L2

There are other changes too that might open up. I wanted to solicit feedback for this before going forward with this change.

**Comment by PMeira** [comment]
Yeah, we can remove those. It was effectively removed a while ago, and there were almost no downloads from 2.7 even before that.

For the new interface I started adding type annotations too: https://github.com/dss-extensions/dss_python/blob/0.12.x/dss/IObj.py

In that branch, I raised NumPy to version 1.21 because of that, but looking now it seems 1.21 supports only Python >= 3.7. Since the download numbers for 3.6 are not insignificant, it's probably better to include it until Python 3.11 is out, at least, so I'll adjust things to include it. (Nobody is using Python 3.5, so already I removed the tag.)

If nothing major happens, I will try to get the releases rolling over the weekend so we can discuss a few things and collect feedback. And maybe finish #78, since it is a requirement for multi-threading and multiple contexts.

@kdheepak, would you be available next week or so for a quick chat? I can send some material in advance.
