### ISSUE TITLE
DSSException: (#8888) There is no active circuit! Create a circuit and retry.

### ISSUE THREAD

**Issue by Conet1502** [dss-extensions/OpenDSSDirect.py#118]
### Versions

- [x] Python version: 
- [x] Python architecture: 
- [x] Operating system and version: 
- [x] OpenDSSDirect.py version number: 

	```import opendssdirect as dss
from opendssdirect.utils import run_command


run_command(r"Redirect {'C:\\Program Files\\OpenDSS\\IEEETestCases\13Bus\\IEEE13Nodeckt.dss'}")


for i in dss.Circuit.AllBusNames():
    print(i)

	```
I am using Spyder IDE and it returns: 

Returns ' DSSException: (#8888) There is no active circuit! Create a circuit and retry.'  

I am not sure why.

**Comment by PMeira** [comment]
Please use `dss.Text.Command` instead of `run_command`. I'll update our examples soon to use that to avoid this kind of issue; namely, `run_command` doesn't raise exceptions so many users just ignore the errors reported on its output. Using that, you should get this instead:

```
dss._cffi_api_util.DSSException: (#243) Redirect file not found: "'C:\Program Files\OpenDSS\IEEETestCases\13Bus\IEEE13Nodeckt.dss'"
```

So, the actual error is in: `Redirect {'C:\Program Files\OpenDSS\IEEETestCases\13Bus\IEEE13Nodeckt.dss'}`. You're using two levels of "quotes" (`{}` and `''`). Remove either of the pairs and it should work, assuming the file exists, i.e., either of these should work:

```python
dss.Text.Command(r"Redirect {C:\Program Files\OpenDSS\IEEETestCases\13Bus\IEEE13Nodeckt.dss}")
dss.Text.Command(r"Redirect 'C:\Program Files\OpenDSS\IEEETestCases\13Bus\IEEE13Nodeckt.dss'")
```

(You'd get a similar error message when running on the official OpenDSS.)
