### ISSUE TITLE
How to scaled up distribution loads

### ISSUE THREAD

**Issue by Cmt111** [dss-extensions/OpenDSSDirect.py#127]
### Versions

- [ ] Python version: 
- [ ] Python architecture: 
- [ ] Operating system and version: 
- [ ] OpenDSSDirect.py version number: 

### Feature Request

I am expecting to expand the distribution network loads.
I have expanded each load of the  IEEE8500 node network by 2 times, then there are problems of many nodes' voltage exceeding the limit, but I do not want to expand the constraint range of my voltage. The following is my program to expand the load. How to solve this problem, please?
![image](https://github.com/dss-extensions/OpenDSSDirect.py/assets/131362179/11af0d87-76a9-47ec-959b-ff5b34651ef6)

**Comment by PMeira** [comment]
(We recommend using https://github.com/orgs/dss-extensions/discussions for general questions.)

Note that you're scaling only the active power. For this circuit, that's enough since the loads are defined by kW and PF, so the kvar is scaled automatically.

You could use [opendssdirect.Solution.LoadMult()](https://dss-extensions.org/OpenDSSDirect.py/opendssdirect.html#opendssdirect.Solution.LoadMult) instead of manually scaling each load.

> How to solve this problem, please?

I wouldn't consider it a problem. That's just how it works. It's a very open question though.

>  I do not want to expand the constraint range of my voltage

Then you're only left with the option of changing the system to force the voltages to be kept within the normal range, somehow. 

For example, you could add generation (and/or storage), capacitors, and voltage regulators, change the topology (reconfiguration) or replace the lines. This system already include some VRs and capacitors, so you could start by tweaking those and the transformer taps directly. 

Depending on how far you want to go, there are lots of papers published around this topic.
