### ISSUE TITLE
'ICapacitors' object has no attribute 'Phases'

### ISSUE THREAD

**Issue by nlaws-camus** [dss-extensions/OpenDSSDirect.py#135]
### Feature Request
It would be very helpful if the Capacitors interface included all the OpenDSS attributes including `phases`.

**Comment by PMeira** [comment]
We're trying to avoid adding new items to the classic API since EPRI has been changing things there. If the capacitor is the latest activated element, you can use `CktElement.NumPhases()`:

```python
>>> from opendssdirect import dss as odd
>>> odd("redirect electricdss-tst/Version8/Distrib/EPRITestCircuits/ckt24/master_ckt24.dss")
>>> odd.Capacitors.AllNames()
['cap_g2100pl6500', 'cap_g2100fk7800', 'cap_g2101ae7400']
>>> odd.Capacitors.Name()
'cap_g2101ae7400'
>>> odd.Capacitors.Name('cap_g2100fk7800')
>>> odd.CktElement.Name() # just checking
'Capacitor.cap_g2100fk7800'
>>> odd.CktElement.NumPhases()
3
```

See https://dss-extensions.org/classic_api.html#the-active-paradigm for some more details on the "Active..." paradigm the classic API uses.

For our engine, we're planning to add a bit more integration with AltDSS-Python to allow something like `odd.Capacitors.to_altdss()` to get an object for the current capacitor (same for other types of elements), which contains most data and related functions in a single place. The low-level API is already implemented, but we still need some updates in the Python code.
