### ISSUE TITLE
Add numpy and scipy as optional dependencies

### ISSUE THREAD

**Issue by kdheepak** [dss-extensions/OpenDSSDirect.py#60]
It'd be nice if the respective functions returned numpy arrays instead of lists, with an option to toggle back behaviour. We can even make it optional dependencies, the way Pandas is at the moment. A part of me wants to just commit to using NumPy and SciPy always, but I'm worried about installation issues and breaking existing code. @PMeira do you have any thoughts on this?

**Comment by PMeira** [comment]
@kdheepak Although you probably could install DSS Python without NumPy as a dependency for ODD.py, it does depend on NumPy (we'd need to change `_cffi_api_util.py` a bit to keep it optional). If you haven't got any complaints so far, almost 6 months since the migration, I think it's fine to depend on it explicitly.

Unless people depended on the specific type of the results being lists, most operations that apply to lists would be fine with NumPy arrays. In the future ODD.py could reshape the matrix results instead of using vectors, and that's the only way I can imagine it would break backwards compatibility.

In the past, most issues with NumPy were due to its dependency on the platform BLAS libs. Nowadays NumPy distributes binary wheels for all major platforms. Also, if we were to switch to Cython instead of CFFI at some point, it'd need NumPy too.

> with an option to toggle back behaviour.

We could do that. With the exception of a couple of functions that do some explicit array manipulations, just patching the `CffiApiUtil` class would be enough to achieve it, even after the instance is already created (much like `use_com_compat` patches the `Base` class in DSS Python).

As soon as I finish the plot integration, we will also depend (optionally) on matplotlib for the plot commands -- I'll finish this as soon as there's nothing more urgent to fix.

Related: 
- https://github.com/dss-extensions/dss_python/issues/13
- https://github.com/dss-extensions/dss_python/issues/2
