### ISSUE TITLE
Silent failing when Loadshapes not read correctly

### ISSUE THREAD

**Issue by tarekelgindy** [dss-extensions/OpenDSSDirect.py#69]
Hi there,

I've recently discovered that if the Loadshape information isnt' specified correctly, OpenDSSDirect will continue to work as expected but won't read in any of the elements after the missing element.

For example if there are 10 loadshapes and the 7th loadshape has a yearly profile that can't be found in the specifed directory, the remaining 3 profiles won't be read. OpenDSSdirect doesn't crash or give warnings about this so it can be difficult to debug this.

Are you aware of this issue? Would it be possible to add errors or warnings when this happens?

**Comment by PMeira** [comment]
@tarekelgindy There are some things that could be happening here.

OpenDSS has a couple of [error functions](https://dss-extensions.org/OpenDSSDirect.py/opendssdirect.html#module-opendssdirect.Error). If it failed properly, it should list an error number (non-zero) in `opendssdirect.Error.Number()`. OpenDSSDirect.py doesn't process it automatically in most functions, only in a couple of places, so you might need to check it manually. I added more error checking in dss_python (the base module that exposes a more COM-like API) exactly because of the issue you mention -- some issues happen even with the official COM module and can lead to unexpected behavior. We should add this kind of error checking in OpenDSSDirect.py as soon as time permits, as well as complement the API with the stable features from DSS C-API.

If an error number is not present in `opendssdirect.Error.Number()`, it's probably related to some bugfix or feature not included in the version of OpenDSSDirect.py/dss_python you're using. This was introduced somewhat recently (related things [here](https://github.com/dss-extensions/dss_capi/blob/master/docs/known_differences.md)):

> The DSS_CAPI_EARLY_ABORT environment variable (also controlled through DSS_Set_EarlyAbort): Controls the DSS script error-handling behavior. If a warning or error occurs and early abortion is enabled (default), the processing of the script is always halted. Otherwise, the processing of the script continues until a major error occurs or it finishes.

`EarlyAbort` is not exposed in OpenDSSDirect.py yet, but you can safely import dss_python to check its value and toggle it if necessary (the OpenDSS instance is shared between the two modules):

``` python
import dss as dss_python
print(dss_python.DSS.Error.EarlyAbort)
dss_python.DSS.Error.EarlyAbort = True
``` 

If the print returns `False` or the `EarlyAbort` property doesn't exist here, you probably should update `dss_python` to the latest version (`pip install --upgrade dss_python` should do it).
